captainVersion: 4
networks:
    search:
        driver: bridge
services:
    $$cap_appname:
        image: craines/odoo-brasil:$$cap_odoo_version
        volumes:
            - $$cap_appname-odoo:/var/lib/odoo
            - $$cap_appname-addos:/mnt/addons
        restart: always
        environment:
            USER: $$cap_postgres_user
            PASSWORD: $$cap_postgres_password
            HOST: $$cap_postgres_host
            PORT: $$cap_postgres_port
            ODOO_PASSWORD: $$cap_master_password
            ODOO_PORT: '8069'
        caproverExtra:
            containerHttpPort: '8069'
caproverOneClickApp:
    displayName: 'Odoo 15 Brasil No Database'
    variables:
        - id: $$cap_postgres_user
          label: Postgres user
          description: 'Set user for postgres'
          validRegex: /.{1,}/
        - id: $$cap_postgres_host
          label: Postgres host
          description: 'Set host for postgres'
          validRegex: /.{1,}/
        - id: $$cap_postgres_port
          label: Postgres port
          defaultValue: '5432'
          description: 'Set port for postgres'
          validRegex: /.{1,}/
        - id: $$cap_postgres_password
          label: Postgres Password
          description: ''
          validRegex: /.{1,}/
        - id: $$cap_odoo_version
          label: Odoo Version
          defaultValue: '15.0'
          description: Check out their docker page for the valid tags https://hub.docker.com/_/odoo?tab=tags
          validRegex: /^([^\s^\/])+$/
    instructions:
        start: Odoo is an open source product CRM
        end: Odoo is deployed and the dashboard is available from http://$$cap_appname.$$cap_root_domain.
    isOfficial: true
    description: Odoo, formerly known as OpenERP, is a suite of open-source business apps written in Python and released under the AGPL license.
    documentation: https://hub.docker.com/_/odoo?tab=description
