captainVersion: 4
networks:
    search:
        driver: bridge
services:
    $$cap_appname:
        image: odoo:$$cap_odoo_version
        volumes:
            - $$cap_appname-odoo-web-data:/var/lib/odoo
            - $$cap_appname-config:/etc/odoo
            - $$cap_appname-addons:/mnt/extra-addons
        restart: always
        environment:
            POSTGRES_USER: $$cap_postgres_user
            POSTGRES_PASSWORD: $$cap_postgres_password
            HOST: $$cap_postgres_host
        caproverExtra:
            containerHttpPort: '8069'
caproverOneClickApp:
    displayName: 'Odoo No Database'
    variables:
        - id: $$cap_postgres_user
          label: Postgres user
          description: 'Set user for postgres'
          validRegex: /.{1,}/
        - id: $$cap_postgres_host
          label: Postgres host
          description: 'Set host for postgres'
          validRegex: /.{1,}/
        - id: $$cap_postgres_password
          label: Postgres Password
          description: ''
          validRegex: /.{1,}/
        - id: $$cap_odoo_version
          label: Odoo Version
          defaultValue: '13.0'
          description: Check out their docker page for the valid tags https://hub.docker.com/_/odoo?tab=tags
          validRegex: /^([^\s^\/])+$/
    instructions:
        start: Odoo is an open source product CRM
        end: Odoo is deployed and the dashboard is available from http://$$cap_appname.$$cap_root_domain.
    isOfficial: true
    description: Odoo, formerly known as OpenERP, is a suite of open-source business apps written in Python and released under the AGPL license.
    documentation: https://hub.docker.com/_/odoo?tab=description
